/**
 * Seed city definitions — 30 cities for V1.
 * Static facts only. Climate data is fetched by the seeder scripts.
 * Priority 1: Himalayan corridor (most critical use case)
 * Priority 2: Major metro origins
 * Priority 3: Coastal, desert, south Indian hill stations
 */

export interface SeedCity {
  city_id: string;
  name: string;
  state: string;
  latitude: number;
  longitude: number;
  altitude_m: number;               // from Open-Elevation or known value
  geological_type: string;
  vegetation_biome: string;
  is_hill_station: boolean;
  is_pilgrimage_site: boolean;
  nearest_aqi_station_km: number;   // estimated; 0 = station in city
  data_coverage_score: number;      // 1–5
}

export const SEED_CITIES: SeedCity[] = [
  // ── PRIORITY 1: Himalayan Corridor ───────────────────────────────
  {
    city_id: 'IXL',
    name: 'Leh',
    state: 'Ladakh',
    latitude: 34.1526,
    longitude: 77.5771,
    altitude_m: 3524,
    geological_type: 'mountain',
    vegetation_biome: 'alpine',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 48,
    data_coverage_score: 2,
  },
  {
    city_id: 'KUU',
    name: 'Manali',
    state: 'Himachal Pradesh',
    latitude: 32.2396,
    longitude: 77.1887,
    altitude_m: 2050,
    geological_type: 'valley',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 60,
    data_coverage_score: 2,
  },
  {
    city_id: 'SLV',
    name: 'Shimla',
    state: 'Himachal Pradesh',
    latitude: 31.1048,
    longitude: 77.1734,
    altitude_m: 2206,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 3,
  },
  {
    city_id: 'DED',
    name: 'Dehradun',
    state: 'Uttarakhand',
    latitude: 30.3165,
    longitude: 78.0322,
    altitude_m: 640,
    geological_type: 'valley',
    vegetation_biome: 'deciduous',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },
  {
    city_id: 'RSH',
    name: 'Rishikesh',
    state: 'Uttarakhand',
    latitude: 30.0869,
    longitude: 78.2676,
    altitude_m: 372,
    geological_type: 'valley',
    vegetation_biome: 'deciduous',
    is_hill_station: false,
    is_pilgrimage_site: true,
    nearest_aqi_station_km: 20,
    data_coverage_score: 3,
  },
  {
    city_id: 'SXR',
    name: 'Srinagar',
    state: 'Jammu & Kashmir',
    latitude: 34.0837,
    longitude: 74.7973,
    altitude_m: 1585,
    geological_type: 'valley',
    vegetation_biome: 'temperate',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 3,
  },
  {
    city_id: 'DAR',
    name: 'Darjeeling',
    state: 'West Bengal',
    latitude: 27.0360,
    longitude: 88.2627,
    altitude_m: 2042,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 50,
    data_coverage_score: 2,
  },
  {
    city_id: 'MSR',
    name: 'Mussoorie',
    state: 'Uttarakhand',
    latitude: 30.4598,
    longitude: 78.0644,
    altitude_m: 2005,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 35,
    data_coverage_score: 2,
  },

  // ── PRIORITY 2: Major Metro Origins ──────────────────────────────
  {
    city_id: 'DEL',
    name: 'Delhi',
    state: 'Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    altitude_m: 216,
    geological_type: 'inland_plains',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'BOM',
    name: 'Mumbai',
    state: 'Maharashtra',
    latitude: 19.0760,
    longitude: 72.8777,
    altitude_m: 14,
    geological_type: 'coastal',
    vegetation_biome: 'coastal_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'BLR',
    name: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    altitude_m: 920,
    geological_type: 'plateau',
    vegetation_biome: 'deciduous',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'CCU',
    name: 'Kolkata',
    state: 'West Bengal',
    latitude: 22.5726,
    longitude: 88.3639,
    altitude_m: 6,
    geological_type: 'inland_plains',
    vegetation_biome: 'tropical_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'MAA',
    name: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    altitude_m: 6,
    geological_type: 'coastal',
    vegetation_biome: 'coastal_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'HYD',
    name: 'Hyderabad',
    state: 'Telangana',
    latitude: 17.3850,
    longitude: 78.4867,
    altitude_m: 542,
    geological_type: 'plateau',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'PNQ',
    name: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    altitude_m: 559,
    geological_type: 'plateau',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'AMD',
    name: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    altitude_m: 53,
    geological_type: 'inland_plains',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 5,
  },
  {
    city_id: 'IXC',
    name: 'Chandigarh',
    state: 'Punjab',
    latitude: 30.7333,
    longitude: 76.7794,
    altitude_m: 321,
    geological_type: 'inland_plains',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },

  // ── PRIORITY 3: Coastal & Desert ─────────────────────────────────
  {
    city_id: 'GOI',
    name: 'Goa',
    state: 'Goa',
    latitude: 15.2993,
    longitude: 74.1240,
    altitude_m: 7,
    geological_type: 'coastal',
    vegetation_biome: 'tropical_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },
  {
    city_id: 'COK',
    name: 'Kochi',
    state: 'Kerala',
    latitude: 9.9312,
    longitude: 76.2673,
    altitude_m: 3,
    geological_type: 'coastal',
    vegetation_biome: 'coastal_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },
  {
    city_id: 'JAI',
    name: 'Jaipur',
    state: 'Rajasthan',
    latitude: 26.9124,
    longitude: 75.7873,
    altitude_m: 431,
    geological_type: 'desert',
    vegetation_biome: 'arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },
  {
    city_id: 'JDH',
    name: 'Jodhpur',
    state: 'Rajasthan',
    latitude: 26.2389,
    longitude: 73.0243,
    altitude_m: 231,
    geological_type: 'desert',
    vegetation_biome: 'arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 3,
  },

  // ── PRIORITY 4: South Indian Hill Stations ────────────────────────
  {
    city_id: 'OOT',
    name: 'Ooty',
    state: 'Tamil Nadu',
    latitude: 11.4102,
    longitude: 76.6950,
    altitude_m: 2240,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 80,
    data_coverage_score: 2,
  },
  {
    city_id: 'MNR',
    name: 'Munnar',
    state: 'Kerala',
    latitude: 10.0889,
    longitude: 77.0595,
    altitude_m: 1600,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 90,
    data_coverage_score: 1,
  },
  {
    city_id: 'CRG',
    name: 'Coorg',
    state: 'Karnataka',
    latitude: 12.3375,
    longitude: 75.8069,
    altitude_m: 1100,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 100,
    data_coverage_score: 1,
  },
  {
    city_id: 'KDK',
    name: 'Kodaikanal',
    state: 'Tamil Nadu',
    latitude: 10.2381,
    longitude: 77.4892,
    altitude_m: 2133,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 85,
    data_coverage_score: 1,
  },

  // ── PRIORITY 5: Northeast India ───────────────────────────────────
  {
    city_id: 'GAU',
    name: 'Guwahati',
    state: 'Assam',
    latitude: 26.1445,
    longitude: 91.7362,
    altitude_m: 55,
    geological_type: 'inland_plains',
    vegetation_biome: 'tropical_humid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 3,
  },
  {
    city_id: 'SHL',
    name: 'Shillong',
    state: 'Meghalaya',
    latitude: 25.5788,
    longitude: 91.8933,
    altitude_m: 1496,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 2,
  },
  {
    city_id: 'GTK',
    name: 'Gangtok',
    state: 'Sikkim',
    latitude: 27.3389,
    longitude: 88.6065,
    altitude_m: 1650,
    geological_type: 'hilly',
    vegetation_biome: 'temperate',
    is_hill_station: true,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 70,
    data_coverage_score: 2,
  },
  {
    city_id: 'UDR',
    name: 'Udaipur',
    state: 'Rajasthan',
    latitude: 24.5854,
    longitude: 73.7125,
    altitude_m: 598,
    geological_type: 'hilly',
    vegetation_biome: 'semi_arid',
    is_hill_station: false,
    is_pilgrimage_site: false,
    nearest_aqi_station_km: 0,
    data_coverage_score: 3,
  },
  {
    city_id: 'VNS',
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    latitude: 25.3176,
    longitude: 82.9739,
    altitude_m: 80,
    geological_type: 'inland_plains',
    vegetation_biome: 'deciduous',
    is_hill_station: false,
    is_pilgrimage_site: true,
    nearest_aqi_station_km: 0,
    data_coverage_score: 4,
  },
];
